server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/emailms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}

  rabbitmq:
    addresses: ${RABBITMQ_ADDRESSES:amqps://SEU_URL_DO_CLOUDAMQP}

broker:
  queue:
    email:
      name: ${BROKER_QUEUE_EMAIL_NAME:default.email}
